In [1]:
from pathlib import Path
import sys

try:
    from src.config import SILVER_OUTPUT_PATH
except ImportError:
    cwd = Path().resolve()
    for p in [cwd, cwd.parent]:
        if (p / "src" / "config.py").exists():
            sys.path.insert(0, str(p))
            break
    from src.config import SILVER_OUTPUT_PATH

import pandas as pd
from IPython.display import display

In [2]:
SILVER_PATH = Path(SILVER_OUTPUT_PATH)
SOURCES = {
    "veiculos": "Veículos (limpos)",
    "motoristas": "Motoristas (limpos)",
    "geocercas": "Geocercas (tabulares)",
    "viagens": "Viagens (limpas)",
    "rastreamento": "Posições GPS (limpas)",
}

for nome, desc in SOURCES.items():
    caminho = SILVER_PATH / nome
    if not caminho.exists():
        print(f"{nome}: (diretório não encontrado)")
        continue
    parquets = list(caminho.glob("*.parquet"))
    if not parquets:
        print(f"{nome}: (sem arquivos parquet)")
        continue
    df = pd.read_parquet(caminho)
    print(f"\n{'='*60}")
    print(f"{nome}  —  {desc}")
    print(f"{'='*60}")
    print(f"Linhas: {len(df):,}  |  Colunas: {len(df.columns)}")
    print()
    print("Colunas e tipos:")
    for c in df.columns:
        missing = df[c].isnull().sum()
        pct = missing / len(df) * 100
        print(f"  {c:30s}  {str(df[c].dtype):15s}  nulos={missing:>5} ({pct:5.1f}%)")
    print()
    print("Primeiras 3 linhas:")
    display(df.head(3))

============================================================
veiculos  —  Veículos (limpos)
============================================================
Linhas: 150  |  Colunas: 11

Colunas e tipos:
  veiculo_id                      str              nulos=    0 (  0.0%)
  placa                           str              nulos=    4 (  2.7%)
  marca                           str              nulos=    0 (  0.0%)
  modelo                          str              nulos=    0 (  0.0%)
  ano_fabricacao                  str              nulos=    0 (  0.0%)
  tipo                            str              nulos=    0 (  0.0%)
  capacidade_kg                   str              nulos=    0 (  0.0%)
  capacidade_paletes              str              nulos=    0 (  0.0%)
  km_atual                        str              nulos=    0 (  0.0%)
  status                          str              nulos=    0 (  0.0%)
  data_ultima_revisao             object           nulos=    2 (  1.3%)

Primeiras 3 linhas:

,veiculo_id,placa,marca,modelo,ano_fabricacao,tipo,capacidade_kg,capacidade_paletes,km_atual,status,data_ultima_revisao
0,VEI-0001,PFX4S35,Volvo,VM 270,2025,Carreta LS,41500,30,768660,ativo,2025-08-16
1,VEI-0002,XNY3W49,DAF,XF 530,2025,Carreta LS,41500,30,580249,ativo,2026-01-29
2,VEI-0003,RHU8X37,Iveco,Tector,2018,Carreta LS,41500,30,441919,inativo,2025-10-26

============================================================
motoristas  —  Motoristas (limpos)
============================================================
Linhas: 124  |  Colunas: 10

Colunas e tipos:
  motorista_id                    str              nulos=    0 (  0.0%)
  nome                            str              nulos=    4 (  3.2%)
  cpf                             str              nulos=    0 (  0.0%)
  cnh                             str              nulos=    3 (  2.4%)
  categoria_cnh                   str              nulos=    0 (  0.0%)
  validade_cnh                    object           nulos=    1 (  0.8%)
  telefone                        str              nulos=    3 (  2.4%)
  data_admissao                   object           nulos=    0 (  0.0%)
  base_operacional                str              nulos=    0 (  0.0%)
  status                          str              nulos=    0 (  0.0%)

Primeiras 3 linhas:

,motorista_id,nome,cpf,cnh,categoria_cnh,validade_cnh,telefone,data_admissao,base_operacional,status
0,MOT-0001,NaN,425.078.619-67,56323299783,D,2025-10-23,+55 (071) 2827-1996,2022-01-15,CD Goiânia - Aparecida,ativo
1,MOT-0002,Nicolas Sousa,795.426.108-58,95800408566,E,2027-10-10,81 0878 5042,2023-11-03,CD Recife - Jaboatão,ativo
2,MOT-0003,João Guilherme da Conceição,367.240.981-22,69937859375,D,2026-09-01,+55 (031) 9373 4768,2026-01-10,CD Belo Horizonte - Contagem,afastado

============================================================
geocercas  —  Geocercas (tabulares)
============================================================
Linhas: 38  |  Colunas: 7

Colunas e tipos:
  geocerca_id                     str              nulos=    0 (  0.0%)
  nome                            str              nulos=    0 (  0.0%)
  tipo                            str              nulos=    0 (  0.0%)
  uf                              str              nulos=   10 ( 26.3%)
  raio_km                         float64          nulos=    0 (  0.0%)
  ativo                           bool             nulos=    0 (  0.0%)
  geometry                        object           nulos=    0 (  0.0%)

Primeiras 3 linhas:

,geocerca_id,nome,tipo,uf,raio_km,ativo,geometry
0,GEO-0001,CD São Paulo - Guarulhos,centro_distribuicao,SP,1.0,True,"{'coordinates': [[[-46.4731 -23.426617], [-4..."
1,GEO-0002,CD Curitiba - CIC,centro_distribuicao,PR,1.0,True,"{'coordinates': [[[-49.3588 -25.486017], [-4..."
2,GEO-0003,CD Rio de Janeiro - Duque de Caxias,centro_distribuicao,RJ,1.0,True,"{'coordinates': [[[-43.3117 -22.776617], [-4..."

============================================================
viagens  —  Viagens (limpas)
============================================================
Linhas: 3,000  |  Colunas: 13

Colunas e tipos:
  viagem_id                       str              nulos=    0 (  0.0%)
  veiculo_id                      str              nulos=    0 (  0.0%)
  motorista_id                    str              nulos=    0 (  0.0%)
  geocerca_origem_id              str              nulos=    0 (  0.0%)
  geocerca_destino_id             str              nulos=    0 (  0.0%)
  data_inicio                     datetime64[ns]   nulos=   49 (  1.6%)
  data_fim_prevista               datetime64[ns]   nulos=    0 (  0.0%)
  data_fim_real                   datetime64[ns]   nulos= 1025 ( 34.2%)
  status                          str              nulos=    0 (  0.0%)
  distancia_km                    str              nulos=    0 (  0.0%)
  peso_carga_kg                   str              nulos=    0 (  0.0%)
  nota_fiscal                     str              nulos=    0 (  0.0%)
  referencia_valida               bool             nulos=    0 (  0.0%)

Primeiras 3 linhas:

,viagem_id,veiculo_id,motorista_id,geocerca_origem_id,geocerca_destino_id,data_inicio,data_fim_prevista,data_fim_real,status,distancia_km,peso_carga_kg,nota_fiscal,referencia_valida
0,VIA-000001,VEI-0062,MOT-0054,GEO-0005,GEO-0027,2026-04-28 21:34:51.499012,2026-04-29 15:34:51.499012,NaT,cancelada,697,29358,NF-577810,True
1,VIA-000002,VEI-0114,MOT-0018,GEO-0007,GEO-0023,NaT,2026-04-30 08:39:19.140311,2026-04-30 09:39:19.140311,concluida,1413,981,NF-523426,True
2,VIA-000003,VEI-0116,MOT-0007,GEO-0008,GEO-0033,2026-04-28 21:34:58.588212,2026-05-01 19:34:58.588212,NaT,atrasada,1842,20430,NF-668277,True

============================================================
rastreamento  —  Posições GPS (limpas)
============================================================
Linhas: 54,915  |  Colunas: 9

Colunas e tipos:
  posicao_id                      str              nulos=    0 (  0.0%)
  viagem_id                       str              nulos=    0 (  0.0%)
  veiculo_id                      str              nulos=    0 (  0.0%)
  latitude                        float64          nulos=    0 (  0.0%)
  longitude                       float64          nulos=    0 (  0.0%)
  timestamp                       datetime64[ns]   nulos=    0 (  0.0%)
  velocidade_kmh                  int32            nulos=    0 (  0.0%)
  ignicao                         bool             nulos=    0 (  0.0%)
  odometro_metros                 float64          nulos=    0 (  0.0%)

Primeiras 3 linhas:

,posicao_id,viagem_id,veiculo_id,latitude,longitude,timestamp,velocidade_kmh,ignicao,odometro_metros
0,POS-367FE6FF0F,VIA-000003,VEI-0116,-8.066642,-35.070495,2026-04-28 21:34:58.588212,41,True,0.0
1,POS-4B86DF1893,VIA-000003,VEI-0116,-9.151663,-35.872785,2026-04-28 21:54:58.588212,81,True,92100.0
2,POS-8F3A7D3A3A,VIA-000003,VEI-0116,-10.105526,-36.796411,2026-04-28 22:12:58.588212,107,True,184200.0

In [3]:
print("=== RESUMO COMPARATIVO BRONZE → SILVER ===")
print()

for nome, desc in SOURCES.items():
    bronze = Path(str(SILVER_PATH).replace("silver", "bronze")) / nome
    silver = SILVER_PATH / nome

    if not bronze.exists() or not silver.exists():
        continue

    b = pd.read_parquet(bronze)
    s = pd.read_parquet(silver)

    diff = len(b) - len(s)
    novos = sorted(set(s.columns) - set(b.columns))
    removidos = sorted(set(b.columns) - set(s.columns))

    print(f"{nome:15s}  bronze={len(b):>6}  silver={len(s):>6}  dif={diff:>+6}  "
          f"colunas novas={novos}  colunas removidas={removidos}")

=== RESUMO COMPARATIVO BRONZE → SILVER ===

veiculos         bronze=   150  silver=   150  dif=    +0  colunas novas=[]  colunas removidas=[]
motoristas       bronze=   124  silver=   124  dif=    +0  colunas novas=[]  colunas removidas=[]
geocercas        bronze=    38  silver=    38  dif=    +0  colunas novas=['ativo', 'geocerca_id', 'nome', 'raio_km', 'tipo', 'uf']  colunas removidas=['properties']
viagens          bronze=  3000  silver=  3000  dif=    +0  colunas novas=['referencia_valida']  colunas removidas=[]
rastreamento     bronze= 56182  silver= 54915  dif= +1267  colunas novas=[]  colunas removidas=[]